/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This file was autogenerated and should not be edited
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */
#ifndef _SO_PRIVATE_OTHERMETHOD_H
#define _SO_PRIVATE_OTHERMETHOD_H

#include <libxml/xmlwriter.h>

#include <so/private/Table.h>

struct so_OtherMethod {
	char *method;
	so_Table *Mean;
	so_Table *Median;
	int in_Mean;
	int in_Median;
	int reference_count;
};

int so_OtherMethod_start_element(so_OtherMethod *self, const char *localname, int nb_attributes, const char **attributes);
void so_OtherMethod_end_element(so_OtherMethod *self, const char *localname);
int so_OtherMethod_characters(so_OtherMethod *self, const char *ch, int len);
int so_OtherMethod_xml(so_OtherMethod *self, xmlTextWriterPtr writer);
int so_OtherMethod_init_attributes(so_OtherMethod *self, int nb_attributes, const char **attributes);

#endif
