/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This file was autogenerated and should not be edited
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <R.h>
#include <Rdefines.h>
#include <so.h>
#include "soc.h"

SEXP r_so_PrecisionIndividualEstimates_new()
{
	so_PrecisionIndividualEstimates *obj = so_PrecisionIndividualEstimates_new();
	if (!obj) {
		error("Failed to create so_PrecisionIndividualEstimates object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_PrecisionIndividualEstimates_copy(SEXP self)
{
	so_PrecisionIndividualEstimates *obj = so_PrecisionIndividualEstimates_copy(R_ExternalPtrAddr(self));
	if (!obj) {
		error("Failed to copy so_PrecisionIndividualEstimates object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_PrecisionIndividualEstimates_free(SEXP self)
{
	so_PrecisionIndividualEstimates_free(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_PrecisionIndividualEstimates_ref(SEXP self)
{
	so_PrecisionIndividualEstimates_ref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_PrecisionIndividualEstimates_unref(SEXP self)
{
	so_PrecisionIndividualEstimates_unref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_PrecisionIndividualEstimates_get_StandardDeviation(SEXP self)
{
	so_Table *child = so_PrecisionIndividualEstimates_get_StandardDeviation(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_PrecisionIndividualEstimates_set_StandardDeviation(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_PrecisionIndividualEstimates_set_StandardDeviation(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_PrecisionIndividualEstimates_create_StandardDeviation(SEXP self)
{
	so_Table *child = so_PrecisionIndividualEstimates_create_StandardDeviation(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

SEXP r_so_PrecisionIndividualEstimates_get_PercentilesCI(SEXP self)
{
	so_Table *child = so_PrecisionIndividualEstimates_get_PercentilesCI(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_PrecisionIndividualEstimates_set_PercentilesCI(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_PrecisionIndividualEstimates_set_PercentilesCI(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_PrecisionIndividualEstimates_create_PercentilesCI(SEXP self)
{
	so_Table *child = so_PrecisionIndividualEstimates_create_PercentilesCI(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

