/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This file was autogenerated and should not be edited
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <R.h>
#include <Rdefines.h>
#include <so.h>
#include "soc.h"

SEXP r_so_RandomEffects_IE_new()
{
	so_RandomEffects_IE *obj = so_RandomEffects_IE_new();
	if (!obj) {
		error("Failed to create so_RandomEffects_IE object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_RandomEffects_IE_copy(SEXP self)
{
	so_RandomEffects_IE *obj = so_RandomEffects_IE_copy(R_ExternalPtrAddr(self));
	if (!obj) {
		error("Failed to copy so_RandomEffects_IE object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_RandomEffects_IE_free(SEXP self)
{
	so_RandomEffects_IE_free(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_ref(SEXP self)
{
	so_RandomEffects_IE_ref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_unref(SEXP self)
{
	so_RandomEffects_IE_unref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_get_EffectMean(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_get_EffectMean(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_RandomEffects_IE_set_EffectMean(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_RandomEffects_IE_set_EffectMean(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_create_EffectMean(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_create_EffectMean(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

SEXP r_so_RandomEffects_IE_get_EffectMedian(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_get_EffectMedian(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_RandomEffects_IE_set_EffectMedian(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_RandomEffects_IE_set_EffectMedian(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_create_EffectMedian(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_create_EffectMedian(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

SEXP r_so_RandomEffects_IE_get_EffectMode(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_get_EffectMode(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_RandomEffects_IE_set_EffectMode(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_RandomEffects_IE_set_EffectMode(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_create_EffectMode(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_create_EffectMode(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

SEXP r_so_RandomEffects_IE_get_Samples(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_get_Samples(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_RandomEffects_IE_set_Samples(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_RandomEffects_IE_set_Samples(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_RandomEffects_IE_create_Samples(SEXP self)
{
	so_Table *child = so_RandomEffects_IE_create_Samples(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

