/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This file was autogenerated and should not be edited
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <R.h>
#include <Rdefines.h>
#include <so.h>
#include "soc.h"

SEXP r_so_ModelDiagnostic_new()
{
	so_ModelDiagnostic *obj = so_ModelDiagnostic_new();
	if (!obj) {
		error("Failed to create so_ModelDiagnostic object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_ModelDiagnostic_copy(SEXP self)
{
	so_ModelDiagnostic *obj = so_ModelDiagnostic_copy(R_ExternalPtrAddr(self));
	if (!obj) {
		error("Failed to copy so_ModelDiagnostic object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_ModelDiagnostic_free(SEXP self)
{
	so_ModelDiagnostic_free(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_ModelDiagnostic_ref(SEXP self)
{
	so_ModelDiagnostic_ref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_ModelDiagnostic_unref(SEXP self)
{
	so_ModelDiagnostic_unref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_ModelDiagnostic_get_DiagnosticStructuralModel(SEXP self)
{
	so_DiagnosticStructuralModel *child = so_ModelDiagnostic_get_DiagnosticStructuralModel(R_ExternalPtrAddr(self));
	SEXP result = R_MakeExternalPtr(child, R_NilValue, R_NilValue);
	return result;
}

SEXP r_so_ModelDiagnostic_set_DiagnosticStructuralModel(SEXP self, SEXP child)
{
	so_ModelDiagnostic_set_DiagnosticStructuralModel(R_ExternalPtrAddr(self), R_ExternalPtrAddr(child));
	return R_NilValue;
}

SEXP r_so_ModelDiagnostic_create_DiagnosticStructuralModel(SEXP self)
{
	so_DiagnosticStructuralModel *child = so_ModelDiagnostic_create_DiagnosticStructuralModel(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

SEXP r_so_ModelDiagnostic_get_DiagnosticIndividualParams(SEXP self)
{
	so_DiagnosticIndividualParams *child = so_ModelDiagnostic_get_DiagnosticIndividualParams(R_ExternalPtrAddr(self));
	SEXP result = R_MakeExternalPtr(child, R_NilValue, R_NilValue);
	return result;
}

SEXP r_so_ModelDiagnostic_set_DiagnosticIndividualParams(SEXP self, SEXP child)
{
	so_ModelDiagnostic_set_DiagnosticIndividualParams(R_ExternalPtrAddr(self), R_ExternalPtrAddr(child));
	return R_NilValue;
}

SEXP r_so_ModelDiagnostic_create_DiagnosticIndividualParams(SEXP self)
{
	so_DiagnosticIndividualParams *child = so_ModelDiagnostic_create_DiagnosticIndividualParams(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

