/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This file was autogenerated and should not be edited
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <R.h>
#include <Rdefines.h>
#include <so.h>
#include "soc.h"

SEXP r_so_DiagnosticStructuralModel_new()
{
	so_DiagnosticStructuralModel *obj = so_DiagnosticStructuralModel_new();
	if (!obj) {
		error("Failed to create so_DiagnosticStructuralModel object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_DiagnosticStructuralModel_copy(SEXP self)
{
	so_DiagnosticStructuralModel *obj = so_DiagnosticStructuralModel_copy(R_ExternalPtrAddr(self));
	if (!obj) {
		error("Failed to copy so_DiagnosticStructuralModel object");
	}
	return R_MakeExternalPtr(obj, R_NilValue, R_NilValue);
}

SEXP r_so_DiagnosticStructuralModel_free(SEXP self)
{
	so_DiagnosticStructuralModel_free(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_DiagnosticStructuralModel_ref(SEXP self)
{
	so_DiagnosticStructuralModel_ref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_DiagnosticStructuralModel_unref(SEXP self)
{
	so_DiagnosticStructuralModel_unref(R_ExternalPtrAddr(self));
	return R_NilValue;
}

SEXP r_so_DiagnosticStructuralModel_get_IndivObservationPrediction(SEXP self)
{
	so_Table *child = so_DiagnosticStructuralModel_get_IndivObservationPrediction(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_DiagnosticStructuralModel_set_IndivObservationPrediction(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_DiagnosticStructuralModel_set_IndivObservationPrediction(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_DiagnosticStructuralModel_create_IndivObservationPrediction(SEXP self)
{
	so_Table *child = so_DiagnosticStructuralModel_create_IndivObservationPrediction(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

SEXP r_so_DiagnosticStructuralModel_get_VPC(SEXP self)
{
	so_Table *child = so_DiagnosticStructuralModel_get_VPC(R_ExternalPtrAddr(self));
	SEXP result = table2df(child);
	return result;
}

SEXP r_so_DiagnosticStructuralModel_set_VPC(SEXP self, SEXP child)
{
	so_Table *table = df2table(child);
	so_DiagnosticStructuralModel_set_VPC(R_ExternalPtrAddr(self), table);
	return R_NilValue;
}

SEXP r_so_DiagnosticStructuralModel_create_VPC(SEXP self)
{
	so_Table *child = so_DiagnosticStructuralModel_create_VPC(R_ExternalPtrAddr(self));
	return R_MakeExternalPtr(child, R_NilValue, R_NilValue);
}

