# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_MissingData_new <- function() {
	obj = .Call("r_so_MissingData_new")
}

so_MissingData_copy <- function(self) {
	.Call("r_so_MissingData_copy", self)
}

so_MissingData_free <- function(self) {
	.Call("r_so_MissingData_free", self)
}

so_MissingData_ref <- function(self) {
	.Call("r_so_MissingData_ref", self)
}

so_MissingData_unref <- function(self) {
	.Call("r_so_MissingData_unref", self)
}

so_MissingData_get_dataCode <- function(self) {
	.Call("r_so_MissingData_get_dataCode", self)
}

so_MissingData_set_dataCode <- function(self, value) {
	.Call("r_so_MissingData_set_dataCode", self, value)
}

so_MissingData_get_missingDataType <- function(self) {
	.Call("r_so_MissingData_get_missingDataType", self)
}

so_MissingData_set_missingDataType <- function(self, value) {
	.Call("r_so_MissingData_set_missingDataType", self, value)
}

dataCode_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_MissingData_get_dataCode(.self$.cobj)
		} else {
			stopifnot(is.character(value), length(value) == 1)
			so_MissingData_set_dataCode(.self$.cobj, value)
		}
	}
}

missingDataType_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_MissingData_get_missingDataType(.self$.cobj)
		} else {
			stopifnot(is.character(value), length(value) == 1)
			so_MissingData_set_missingDataType(.self$.cobj, value)
		}
	}
}

so_MissingData = setRefClass("so_MissingData",
	fields=list(
		dataCode = dataCode_acc,
		missingDataType = missingDataType_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_MissingData_copy(.self$.cobj)
			so_MissingData$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_MissingData_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_MissingData_unref(.self$.cobj)
		}
	)
)
