# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_Bayesian_PPE_new <- function() {
	obj = .Call("r_so_Bayesian_PPE_new")
}

so_Bayesian_PPE_copy <- function(self) {
	.Call("r_so_Bayesian_PPE_copy", self)
}

so_Bayesian_PPE_free <- function(self) {
	.Call("r_so_Bayesian_PPE_free", self)
}

so_Bayesian_PPE_ref <- function(self) {
	.Call("r_so_Bayesian_PPE_ref", self)
}

so_Bayesian_PPE_unref <- function(self) {
	.Call("r_so_Bayesian_PPE_unref", self)
}

so_Bayesian_PPE_get_StandardDeviationPosterior <- function(self) {
	.Call("r_so_Bayesian_PPE_get_StandardDeviationPosterior", self)
}

so_Bayesian_PPE_set_StandardDeviationPosterior <- function(self, value) {
	.Call("r_so_Bayesian_PPE_set_StandardDeviationPosterior", self, value)
}

so_Bayesian_PPE_create_StandardDeviationPosterior <- function(self) {
	.Call("r_so_Bayesian_PPE_create_StandardDeviationPosterior", self)
}

so_Bayesian_PPE_get_PercentilesCI <- function(self) {
	.Call("r_so_Bayesian_PPE_get_PercentilesCI", self)
}

so_Bayesian_PPE_set_PercentilesCI <- function(self, value) {
	.Call("r_so_Bayesian_PPE_set_PercentilesCI", self, value)
}

so_Bayesian_PPE_create_PercentilesCI <- function(self) {
	.Call("r_so_Bayesian_PPE_create_PercentilesCI", self)
}

StandardDeviationPosterior_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_Bayesian_PPE_get_StandardDeviationPosterior(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_Bayesian_PPE_set_StandardDeviationPosterior(.self$.cobj, value)
		}
	}
}

PercentilesCI_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_Bayesian_PPE_get_PercentilesCI(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_Bayesian_PPE_set_PercentilesCI(.self$.cobj, value)
		}
	}
}

so_Bayesian_PPE = setRefClass("so_Bayesian_PPE",
	fields=list(
		StandardDeviationPosterior = StandardDeviationPosterior_acc,
		PercentilesCI = PercentilesCI_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_Bayesian_PPE_copy(.self$.cobj)
			so_Bayesian_PPE$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_Bayesian_PPE_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_Bayesian_PPE_unref(.self$.cobj)
		}
	)
)
