# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_ModelDiagnostic_new <- function() {
	obj = .Call("r_so_ModelDiagnostic_new")
}

so_ModelDiagnostic_copy <- function(self) {
	.Call("r_so_ModelDiagnostic_copy", self)
}

so_ModelDiagnostic_free <- function(self) {
	.Call("r_so_ModelDiagnostic_free", self)
}

so_ModelDiagnostic_ref <- function(self) {
	.Call("r_so_ModelDiagnostic_ref", self)
}

so_ModelDiagnostic_unref <- function(self) {
	.Call("r_so_ModelDiagnostic_unref", self)
}

so_ModelDiagnostic_get_DiagnosticStructuralModel <- function(self) {
	.Call("r_so_ModelDiagnostic_get_DiagnosticStructuralModel", self)
}

so_ModelDiagnostic_set_DiagnosticStructuralModel <- function(self, value) {
	.Call("r_so_ModelDiagnostic_set_DiagnosticStructuralModel", self, value)
}

so_ModelDiagnostic_create_DiagnosticStructuralModel <- function(self) {
	.Call("r_so_ModelDiagnostic_create_DiagnosticStructuralModel", self)
}

so_ModelDiagnostic_get_DiagnosticIndividualParams <- function(self) {
	.Call("r_so_ModelDiagnostic_get_DiagnosticIndividualParams", self)
}

so_ModelDiagnostic_set_DiagnosticIndividualParams <- function(self, value) {
	.Call("r_so_ModelDiagnostic_set_DiagnosticIndividualParams", self, value)
}

so_ModelDiagnostic_create_DiagnosticIndividualParams <- function(self) {
	.Call("r_so_ModelDiagnostic_create_DiagnosticIndividualParams", self)
}

DiagnosticStructuralModel_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_ModelDiagnostic_get_DiagnosticStructuralModel(.self$.cobj)
			if (!isnull(child)) {
				so_DiagnosticStructuralModel_ref(child)
				so_DiagnosticStructuralModel$new(cobj=child)
			}
		} else {
			if (!is(value, "so_DiagnosticStructuralModel")) {
				stop("object must be of type 'so_DiagnosticStructuralModel'")
			}
			so_ModelDiagnostic_set_DiagnosticStructuralModel(.self$.cobj, value$.cobj)
			so_DiagnosticStructuralModel_ref(value$.cobj)
		}
	}
}

DiagnosticIndividualParams_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_ModelDiagnostic_get_DiagnosticIndividualParams(.self$.cobj)
			if (!isnull(child)) {
				so_DiagnosticIndividualParams_ref(child)
				so_DiagnosticIndividualParams$new(cobj=child)
			}
		} else {
			if (!is(value, "so_DiagnosticIndividualParams")) {
				stop("object must be of type 'so_DiagnosticIndividualParams'")
			}
			so_ModelDiagnostic_set_DiagnosticIndividualParams(.self$.cobj, value$.cobj)
			so_DiagnosticIndividualParams_ref(value$.cobj)
		}
	}
}

so_ModelDiagnostic = setRefClass("so_ModelDiagnostic",
	fields=list(
		DiagnosticStructuralModel = DiagnosticStructuralModel_acc,
		DiagnosticIndividualParams = DiagnosticIndividualParams_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_ModelDiagnostic_copy(.self$.cobj)
			so_ModelDiagnostic$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_ModelDiagnostic_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_ModelDiagnostic_unref(.self$.cobj)
		}
	)
)
