# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_Residuals_new <- function() {
	obj = .Call("r_so_Residuals_new")
}

so_Residuals_copy <- function(self) {
	.Call("r_so_Residuals_copy", self)
}

so_Residuals_free <- function(self) {
	.Call("r_so_Residuals_free", self)
}

so_Residuals_ref <- function(self) {
	.Call("r_so_Residuals_ref", self)
}

so_Residuals_unref <- function(self) {
	.Call("r_so_Residuals_unref", self)
}

so_Residuals_get_ResidualTable <- function(self) {
	.Call("r_so_Residuals_get_ResidualTable", self)
}

so_Residuals_set_ResidualTable <- function(self, value) {
	.Call("r_so_Residuals_set_ResidualTable", self, value)
}

so_Residuals_create_ResidualTable <- function(self) {
	.Call("r_so_Residuals_create_ResidualTable", self)
}

so_Residuals_get_EpsShrinkage <- function(self) {
	.Call("r_so_Residuals_get_EpsShrinkage", self)
}

so_Residuals_set_EpsShrinkage <- function(self, value) {
	.Call("r_so_Residuals_set_EpsShrinkage", self, value)
}

so_Residuals_create_EpsShrinkage <- function(self) {
	.Call("r_so_Residuals_create_EpsShrinkage", self)
}

ResidualTable_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_Residuals_get_ResidualTable(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_Residuals_set_ResidualTable(.self$.cobj, value)
		}
	}
}

EpsShrinkage_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_Residuals_get_EpsShrinkage(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_Residuals_set_EpsShrinkage(.self$.cobj, value)
		}
	}
}

so_Residuals = setRefClass("so_Residuals",
	fields=list(
		ResidualTable = ResidualTable_acc,
		EpsShrinkage = EpsShrinkage_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_Residuals_copy(.self$.cobj)
			so_Residuals$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_Residuals_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_Residuals_unref(.self$.cobj)
		}
	)
)
