# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_RandomEffects_IE_new <- function() {
	obj = .Call("r_so_RandomEffects_IE_new")
}

so_RandomEffects_IE_copy <- function(self) {
	.Call("r_so_RandomEffects_IE_copy", self)
}

so_RandomEffects_IE_free <- function(self) {
	.Call("r_so_RandomEffects_IE_free", self)
}

so_RandomEffects_IE_ref <- function(self) {
	.Call("r_so_RandomEffects_IE_ref", self)
}

so_RandomEffects_IE_unref <- function(self) {
	.Call("r_so_RandomEffects_IE_unref", self)
}

so_RandomEffects_IE_get_EffectMean <- function(self) {
	.Call("r_so_RandomEffects_IE_get_EffectMean", self)
}

so_RandomEffects_IE_set_EffectMean <- function(self, value) {
	.Call("r_so_RandomEffects_IE_set_EffectMean", self, value)
}

so_RandomEffects_IE_create_EffectMean <- function(self) {
	.Call("r_so_RandomEffects_IE_create_EffectMean", self)
}

so_RandomEffects_IE_get_EffectMedian <- function(self) {
	.Call("r_so_RandomEffects_IE_get_EffectMedian", self)
}

so_RandomEffects_IE_set_EffectMedian <- function(self, value) {
	.Call("r_so_RandomEffects_IE_set_EffectMedian", self, value)
}

so_RandomEffects_IE_create_EffectMedian <- function(self) {
	.Call("r_so_RandomEffects_IE_create_EffectMedian", self)
}

so_RandomEffects_IE_get_EffectMode <- function(self) {
	.Call("r_so_RandomEffects_IE_get_EffectMode", self)
}

so_RandomEffects_IE_set_EffectMode <- function(self, value) {
	.Call("r_so_RandomEffects_IE_set_EffectMode", self, value)
}

so_RandomEffects_IE_create_EffectMode <- function(self) {
	.Call("r_so_RandomEffects_IE_create_EffectMode", self)
}

so_RandomEffects_IE_get_Samples <- function(self) {
	.Call("r_so_RandomEffects_IE_get_Samples", self)
}

so_RandomEffects_IE_set_Samples <- function(self, value) {
	.Call("r_so_RandomEffects_IE_set_Samples", self, value)
}

so_RandomEffects_IE_create_Samples <- function(self) {
	.Call("r_so_RandomEffects_IE_create_Samples", self)
}

EffectMean_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_RandomEffects_IE_get_EffectMean(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_RandomEffects_IE_set_EffectMean(.self$.cobj, value)
		}
	}
}

EffectMedian_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_RandomEffects_IE_get_EffectMedian(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_RandomEffects_IE_set_EffectMedian(.self$.cobj, value)
		}
	}
}

EffectMode_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_RandomEffects_IE_get_EffectMode(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_RandomEffects_IE_set_EffectMode(.self$.cobj, value)
		}
	}
}

Samples_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_RandomEffects_IE_get_Samples(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_RandomEffects_IE_set_Samples(.self$.cobj, value)
		}
	}
}

so_RandomEffects_IE = setRefClass("so_RandomEffects_IE",
	fields=list(
		EffectMean = EffectMean_acc,
		EffectMedian = EffectMedian_acc,
		EffectMode = EffectMode_acc,
		Samples = Samples_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_RandomEffects_IE_copy(.self$.cobj)
			so_RandomEffects_IE$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_RandomEffects_IE_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_RandomEffects_IE_unref(.self$.cobj)
		}
	)
)
