# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_OtherMethod_PPE_new <- function() {
	obj = .Call("r_so_OtherMethod_PPE_new")
}

so_OtherMethod_PPE_copy <- function(self) {
	.Call("r_so_OtherMethod_PPE_copy", self)
}

so_OtherMethod_PPE_free <- function(self) {
	.Call("r_so_OtherMethod_PPE_free", self)
}

so_OtherMethod_PPE_ref <- function(self) {
	.Call("r_so_OtherMethod_PPE_ref", self)
}

so_OtherMethod_PPE_unref <- function(self) {
	.Call("r_so_OtherMethod_PPE_unref", self)
}

so_OtherMethod_PPE_get_CovarianceMatrix <- function(self) {
	.Call("r_so_OtherMethod_PPE_get_CovarianceMatrix", self)
}

so_OtherMethod_PPE_set_CovarianceMatrix <- function(self, value) {
	.Call("r_so_OtherMethod_PPE_set_CovarianceMatrix", self, value)
}

so_OtherMethod_PPE_create_CovarianceMatrix <- function(self) {
	.Call("r_so_OtherMethod_PPE_create_CovarianceMatrix", self)
}

so_OtherMethod_PPE_get_CorrelationMatrix <- function(self) {
	.Call("r_so_OtherMethod_PPE_get_CorrelationMatrix", self)
}

so_OtherMethod_PPE_set_CorrelationMatrix <- function(self, value) {
	.Call("r_so_OtherMethod_PPE_set_CorrelationMatrix", self, value)
}

so_OtherMethod_PPE_create_CorrelationMatrix <- function(self) {
	.Call("r_so_OtherMethod_PPE_create_CorrelationMatrix", self)
}

so_OtherMethod_PPE_get_StandardDeviation <- function(self) {
	.Call("r_so_OtherMethod_PPE_get_StandardDeviation", self)
}

so_OtherMethod_PPE_set_StandardDeviation <- function(self, value) {
	.Call("r_so_OtherMethod_PPE_set_StandardDeviation", self, value)
}

so_OtherMethod_PPE_create_StandardDeviation <- function(self) {
	.Call("r_so_OtherMethod_PPE_create_StandardDeviation", self)
}

so_OtherMethod_PPE_get_StandardError <- function(self) {
	.Call("r_so_OtherMethod_PPE_get_StandardError", self)
}

so_OtherMethod_PPE_set_StandardError <- function(self, value) {
	.Call("r_so_OtherMethod_PPE_set_StandardError", self, value)
}

so_OtherMethod_PPE_create_StandardError <- function(self) {
	.Call("r_so_OtherMethod_PPE_create_StandardError", self)
}

so_OtherMethod_PPE_get_AsymptoticCI <- function(self) {
	.Call("r_so_OtherMethod_PPE_get_AsymptoticCI", self)
}

so_OtherMethod_PPE_set_AsymptoticCI <- function(self, value) {
	.Call("r_so_OtherMethod_PPE_set_AsymptoticCI", self, value)
}

so_OtherMethod_PPE_create_AsymptoticCI <- function(self) {
	.Call("r_so_OtherMethod_PPE_create_AsymptoticCI", self)
}

so_OtherMethod_PPE_get_PercentilesCI <- function(self) {
	.Call("r_so_OtherMethod_PPE_get_PercentilesCI", self)
}

so_OtherMethod_PPE_set_PercentilesCI <- function(self, value) {
	.Call("r_so_OtherMethod_PPE_set_PercentilesCI", self, value)
}

so_OtherMethod_PPE_create_PercentilesCI <- function(self) {
	.Call("r_so_OtherMethod_PPE_create_PercentilesCI", self)
}

CovarianceMatrix_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_OtherMethod_PPE_get_CovarianceMatrix(.self$.cobj)
		} else {
			if (!is(value, "matrix")) {
				stop("object must be of type 'matrix'")
			}
			so_OtherMethod_PPE_set_CovarianceMatrix(.self$.cobj, value)
		}
	}
}

CorrelationMatrix_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_OtherMethod_PPE_get_CorrelationMatrix(.self$.cobj)
		} else {
			if (!is(value, "matrix")) {
				stop("object must be of type 'matrix'")
			}
			so_OtherMethod_PPE_set_CorrelationMatrix(.self$.cobj, value)
		}
	}
}

StandardDeviation_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_OtherMethod_PPE_get_StandardDeviation(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_OtherMethod_PPE_set_StandardDeviation(.self$.cobj, value)
		}
	}
}

StandardError_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_OtherMethod_PPE_get_StandardError(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_OtherMethod_PPE_set_StandardError(.self$.cobj, value)
		}
	}
}

AsymptoticCI_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_OtherMethod_PPE_get_AsymptoticCI(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_OtherMethod_PPE_set_AsymptoticCI(.self$.cobj, value)
		}
	}
}

PercentilesCI_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_OtherMethod_PPE_get_PercentilesCI(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_OtherMethod_PPE_set_PercentilesCI(.self$.cobj, value)
		}
	}
}

so_OtherMethod_PPE = setRefClass("so_OtherMethod_PPE",
	fields=list(
		CovarianceMatrix = CovarianceMatrix_acc,
		CorrelationMatrix = CorrelationMatrix_acc,
		StandardDeviation = StandardDeviation_acc,
		StandardError = StandardError_acc,
		AsymptoticCI = AsymptoticCI_acc,
		PercentilesCI = PercentilesCI_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_OtherMethod_PPE_copy(.self$.cobj)
			so_OtherMethod_PPE$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_OtherMethod_PPE_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_OtherMethod_PPE_unref(.self$.cobj)
		}
	)
)
