# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_TargetToolMessages_new <- function() {
	obj = .Call("r_so_TargetToolMessages_new")
}

so_TargetToolMessages_copy <- function(self) {
	.Call("r_so_TargetToolMessages_copy", self)
}

so_TargetToolMessages_free <- function(self) {
	.Call("r_so_TargetToolMessages_free", self)
}

so_TargetToolMessages_ref <- function(self) {
	.Call("r_so_TargetToolMessages_ref", self)
}

so_TargetToolMessages_unref <- function(self) {
	.Call("r_so_TargetToolMessages_unref", self)
}

so_TargetToolMessages_get_Termination <- function(self) {
	.Call("r_so_TargetToolMessages_get_Termination", self)
}

so_TargetToolMessages_set_Termination <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_Termination", self, value)
}

so_TargetToolMessages_get_Warnings <- function(self) {
	.Call("r_so_TargetToolMessages_get_Warnings", self)
}

so_TargetToolMessages_set_Warnings <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_Warnings", self, value)
}

so_TargetToolMessages_get_Errors <- function(self) {
	.Call("r_so_TargetToolMessages_get_Errors", self)
}

so_TargetToolMessages_set_Errors <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_Errors", self, value)
}

so_TargetToolMessages_get_ElapsedTime <- function(self) {
	.Call("r_so_TargetToolMessages_get_ElapsedTime", self)
}

so_TargetToolMessages_set_ElapsedTime <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_ElapsedTime", self, value)
}

so_TargetToolMessages_get_OutputFilePath <- function(self) {
	.Call("r_so_TargetToolMessages_get_OutputFilePath", self)
}

so_TargetToolMessages_set_OutputFilePath <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_OutputFilePath", self, value)
}

so_TargetToolMessages_create_OutputFilePath <- function(self) {
	.Call("r_so_TargetToolMessages_create_OutputFilePath", self)
}

so_TargetToolMessages_get_ChainsNumber <- function(self) {
	.Call("r_so_TargetToolMessages_get_ChainsNumber", self)
}

so_TargetToolMessages_set_ChainsNumber <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_ChainsNumber", self, value)
}

so_TargetToolMessages_get_IterationNumber <- function(self) {
	.Call("r_so_TargetToolMessages_get_IterationNumber", self)
}

so_TargetToolMessages_set_IterationNumber <- function(self, value) {
	.Call("r_so_TargetToolMessages_set_IterationNumber", self, value)
}

Termination_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_TargetToolMessages_get_Termination(.self$.cobj)
		} else {
			if (!is(value, "character")) {
				stop("object must be of type 'character'")
			}
			so_TargetToolMessages_set_Termination(.self$.cobj, value)
		}
	}
}

Warnings_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_TargetToolMessages_get_Warnings(.self$.cobj)
		} else {
			if (!is(value, "character")) {
				stop("object must be of type 'character'")
			}
			so_TargetToolMessages_set_Warnings(.self$.cobj, value)
		}
	}
}

Errors_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_TargetToolMessages_get_Errors(.self$.cobj)
		} else {
			if (!is(value, "character")) {
				stop("object must be of type 'character'")
			}
			so_TargetToolMessages_set_Errors(.self$.cobj, value)
		}
	}
}

ElapsedTime_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_TargetToolMessages_get_ElapsedTime(.self$.cobj)
		} else {
			if (!is(value, "numeric")) {
				stop("object must be of type 'numeric'")
			}
			so_TargetToolMessages_set_ElapsedTime(.self$.cobj, value)
		}
	}
}

OutputFilePath_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_TargetToolMessages_get_OutputFilePath(.self$.cobj)
			if (!isnull(child)) {
				so_ExternalFile_ref(child)
				so_ExternalFile$new(cobj=child)
			}
		} else {
			if (!is(value, "so_ExternalFile")) {
				stop("object must be of type 'so_ExternalFile'")
			}
			so_TargetToolMessages_set_OutputFilePath(.self$.cobj, value$.cobj)
			so_ExternalFile_ref(value$.cobj)
		}
	}
}

ChainsNumber_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_TargetToolMessages_get_ChainsNumber(.self$.cobj)
		} else {
			if (!is(value, "numeric")) {
				stop("object must be of type 'numeric'")
			}
			so_TargetToolMessages_set_ChainsNumber(.self$.cobj, value)
		}
	}
}

IterationNumber_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_TargetToolMessages_get_IterationNumber(.self$.cobj)
		} else {
			if (!is(value, "numeric")) {
				stop("object must be of type 'numeric'")
			}
			so_TargetToolMessages_set_IterationNumber(.self$.cobj, value)
		}
	}
}

so_TargetToolMessages = setRefClass("so_TargetToolMessages",
	fields=list(
		Termination = Termination_acc,
		Warnings = Warnings_acc,
		Errors = Errors_acc,
		ElapsedTime = ElapsedTime_acc,
		OutputFilePath = OutputFilePath_acc,
		ChainsNumber = ChainsNumber_acc,
		IterationNumber = IterationNumber_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_TargetToolMessages_copy(.self$.cobj)
			so_TargetToolMessages$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_TargetToolMessages_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_TargetToolMessages_unref(.self$.cobj)
		}
	)
)
