# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_PrecisionIndividualEstimates_new <- function() {
	obj = .Call("r_so_PrecisionIndividualEstimates_new")
}

so_PrecisionIndividualEstimates_copy <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_copy", self)
}

so_PrecisionIndividualEstimates_free <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_free", self)
}

so_PrecisionIndividualEstimates_ref <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_ref", self)
}

so_PrecisionIndividualEstimates_unref <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_unref", self)
}

so_PrecisionIndividualEstimates_get_StandardDeviation <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_get_StandardDeviation", self)
}

so_PrecisionIndividualEstimates_set_StandardDeviation <- function(self, value) {
	.Call("r_so_PrecisionIndividualEstimates_set_StandardDeviation", self, value)
}

so_PrecisionIndividualEstimates_create_StandardDeviation <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_create_StandardDeviation", self)
}

so_PrecisionIndividualEstimates_get_PercentilesCI <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_get_PercentilesCI", self)
}

so_PrecisionIndividualEstimates_set_PercentilesCI <- function(self, value) {
	.Call("r_so_PrecisionIndividualEstimates_set_PercentilesCI", self, value)
}

so_PrecisionIndividualEstimates_create_PercentilesCI <- function(self) {
	.Call("r_so_PrecisionIndividualEstimates_create_PercentilesCI", self)
}

StandardDeviation_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_PrecisionIndividualEstimates_get_StandardDeviation(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_PrecisionIndividualEstimates_set_StandardDeviation(.self$.cobj, value)
		}
	}
}

PercentilesCI_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_PrecisionIndividualEstimates_get_PercentilesCI(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_PrecisionIndividualEstimates_set_PercentilesCI(.self$.cobj, value)
		}
	}
}

so_PrecisionIndividualEstimates = setRefClass("so_PrecisionIndividualEstimates",
	fields=list(
		StandardDeviation = StandardDeviation_acc,
		PercentilesCI = PercentilesCI_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_PrecisionIndividualEstimates_copy(.self$.cobj)
			so_PrecisionIndividualEstimates$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_PrecisionIndividualEstimates_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_PrecisionIndividualEstimates_unref(.self$.cobj)
		}
	)
)
