# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_DiagnosticStructuralModel_new <- function() {
	obj = .Call("r_so_DiagnosticStructuralModel_new")
}

so_DiagnosticStructuralModel_copy <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_copy", self)
}

so_DiagnosticStructuralModel_free <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_free", self)
}

so_DiagnosticStructuralModel_ref <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_ref", self)
}

so_DiagnosticStructuralModel_unref <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_unref", self)
}

so_DiagnosticStructuralModel_get_IndivObservationPrediction <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_get_IndivObservationPrediction", self)
}

so_DiagnosticStructuralModel_set_IndivObservationPrediction <- function(self, value) {
	.Call("r_so_DiagnosticStructuralModel_set_IndivObservationPrediction", self, value)
}

so_DiagnosticStructuralModel_create_IndivObservationPrediction <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_create_IndivObservationPrediction", self)
}

so_DiagnosticStructuralModel_get_VPC <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_get_VPC", self)
}

so_DiagnosticStructuralModel_set_VPC <- function(self, value) {
	.Call("r_so_DiagnosticStructuralModel_set_VPC", self, value)
}

so_DiagnosticStructuralModel_create_VPC <- function(self) {
	.Call("r_so_DiagnosticStructuralModel_create_VPC", self)
}

IndivObservationPrediction_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_DiagnosticStructuralModel_get_IndivObservationPrediction(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_DiagnosticStructuralModel_set_IndivObservationPrediction(.self$.cobj, value)
		}
	}
}

VPC_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_DiagnosticStructuralModel_get_VPC(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_DiagnosticStructuralModel_set_VPC(.self$.cobj, value)
		}
	}
}

so_DiagnosticStructuralModel = setRefClass("so_DiagnosticStructuralModel",
	fields=list(
		IndivObservationPrediction = IndivObservationPrediction_acc,
		VPC = VPC_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_DiagnosticStructuralModel_copy(.self$.cobj)
			so_DiagnosticStructuralModel$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_DiagnosticStructuralModel_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_DiagnosticStructuralModel_unref(.self$.cobj)
		}
	)
)
