# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_PopulationEstimates_new <- function() {
	obj = .Call("r_so_PopulationEstimates_new")
}

so_PopulationEstimates_copy <- function(self) {
	.Call("r_so_PopulationEstimates_copy", self)
}

so_PopulationEstimates_free <- function(self) {
	.Call("r_so_PopulationEstimates_free", self)
}

so_PopulationEstimates_ref <- function(self) {
	.Call("r_so_PopulationEstimates_ref", self)
}

so_PopulationEstimates_unref <- function(self) {
	.Call("r_so_PopulationEstimates_unref", self)
}

so_PopulationEstimates_get_MLE <- function(self) {
	.Call("r_so_PopulationEstimates_get_MLE", self)
}

so_PopulationEstimates_set_MLE <- function(self, value) {
	.Call("r_so_PopulationEstimates_set_MLE", self, value)
}

so_PopulationEstimates_create_MLE <- function(self) {
	.Call("r_so_PopulationEstimates_create_MLE", self)
}

so_PopulationEstimates_get_Bayesian <- function(self) {
	.Call("r_so_PopulationEstimates_get_Bayesian", self)
}

so_PopulationEstimates_set_Bayesian <- function(self, value) {
	.Call("r_so_PopulationEstimates_set_Bayesian", self, value)
}

so_PopulationEstimates_create_Bayesian <- function(self) {
	.Call("r_so_PopulationEstimates_create_Bayesian", self)
}

so_PopulationEstimates_get_OtherMethod <- function(self) {
	.Call("r_so_PopulationEstimates_get_OtherMethod", self)
}

so_PopulationEstimates_set_OtherMethod <- function(self, value) {
	.Call("r_so_PopulationEstimates_set_OtherMethod", self, value)
}

so_PopulationEstimates_create_OtherMethod <- function(self) {
	.Call("r_so_PopulationEstimates_create_OtherMethod", self)
}

MLE_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_PopulationEstimates_get_MLE(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_PopulationEstimates_set_MLE(.self$.cobj, value)
		}
	}
}

Bayesian_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_PopulationEstimates_get_Bayesian(.self$.cobj)
			if (!isnull(child)) {
				so_Bayesian_ref(child)
				so_Bayesian$new(cobj=child)
			}
		} else {
			if (!is(value, "so_Bayesian")) {
				stop("object must be of type 'so_Bayesian'")
			}
			so_PopulationEstimates_set_Bayesian(.self$.cobj, value$.cobj)
			so_Bayesian_ref(value$.cobj)
		}
	}
}

OtherMethod_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_PopulationEstimates_get_OtherMethod(.self$.cobj)
			if (!isnull(child)) {
				so_OtherMethod_ref(child)
				so_OtherMethod$new(cobj=child)
			}
		} else {
			if (!is(value, "so_OtherMethod")) {
				stop("object must be of type 'so_OtherMethod'")
			}
			so_PopulationEstimates_set_OtherMethod(.self$.cobj, value$.cobj)
			so_OtherMethod_ref(value$.cobj)
		}
	}
}

so_PopulationEstimates = setRefClass("so_PopulationEstimates",
	fields=list(
		MLE = MLE_acc,
		Bayesian = Bayesian_acc,
		OtherMethod = OtherMethod_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_PopulationEstimates_copy(.self$.cobj)
			so_PopulationEstimates$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_PopulationEstimates_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_PopulationEstimates_unref(.self$.cobj)
		}
	)
)
