# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_SimulationSubType_new <- function() {
	obj = .Call("r_so_SimulationSubType_new")
}

so_SimulationSubType_copy <- function(self) {
	.Call("r_so_SimulationSubType_copy", self)
}

so_SimulationSubType_free <- function(self) {
	.Call("r_so_SimulationSubType_free", self)
}

so_SimulationSubType_ref <- function(self) {
	.Call("r_so_SimulationSubType_ref", self)
}

so_SimulationSubType_unref <- function(self) {
	.Call("r_so_SimulationSubType_unref", self)
}

so_SimulationSubType_get_name <- function(self) {
	.Call("r_so_SimulationSubType_get_name", self)
}

so_SimulationSubType_set_name <- function(self, value) {
	.Call("r_so_SimulationSubType_set_name", self, value)
}

so_SimulationSubType_get_extFileNo <- function(self) {
	.Call("r_so_SimulationSubType_get_extFileNo", self)
}

so_SimulationSubType_set_extFileNo <- function(self, value) {
	.Call("r_so_SimulationSubType_set_extFileNo", self, value)
}

so_SimulationSubType_get_base <- function(self) {
	.Call("r_so_SimulationSubType_get_base", self)
}

so_SimulationSubType_set_base <- function(self, value) {
	.Call("r_so_SimulationSubType_set_base", self, value)
}

name_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_SimulationSubType_get_name(.self$.cobj)
		} else {
			stopifnot(is.character(value), length(value) == 1)
			so_SimulationSubType_set_name(.self$.cobj, value)
		}
	}
}

extFileNo_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_SimulationSubType_get_extFileNo(.self$.cobj)
		} else {
			stopifnot(length(value) == 1)
			value = as.integer(value)
			so_SimulationSubType_set_extFileNo(.self$.cobj, value)
		}
	}
}

base_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_SimulationSubType_get_base(.self$.cobj)
		} else {
			if (!is(value, "Table")) {
				stop("base object must be a 'Table' object")
			}
			so_SimulationSubType_set_base(.self$.cobj, value)
			so_Table_ref(value$.cobj)
		}
	}
}

so_SimulationSubType = setRefClass("so_SimulationSubType",
	fields=list(
		name = name_acc,
		extFileNo = extFileNo_acc,
		base = base_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_SimulationSubType_copy(.self$.cobj)
			so_SimulationSubType$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_SimulationSubType_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_SimulationSubType_unref(.self$.cobj)
		}
	)
)
