# libsoc - Library to handle standardised output files
# Copyright (C) 2015 Rikard Nordgren
# 
# This file was autogenerated and should not be edited
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# his library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

so_IndividualEstimates_new <- function() {
	obj = .Call("r_so_IndividualEstimates_new")
}

so_IndividualEstimates_copy <- function(self) {
	.Call("r_so_IndividualEstimates_copy", self)
}

so_IndividualEstimates_free <- function(self) {
	.Call("r_so_IndividualEstimates_free", self)
}

so_IndividualEstimates_ref <- function(self) {
	.Call("r_so_IndividualEstimates_ref", self)
}

so_IndividualEstimates_unref <- function(self) {
	.Call("r_so_IndividualEstimates_unref", self)
}

so_IndividualEstimates_get_Estimates <- function(self) {
	.Call("r_so_IndividualEstimates_get_Estimates", self)
}

so_IndividualEstimates_set_Estimates <- function(self, value) {
	.Call("r_so_IndividualEstimates_set_Estimates", self, value)
}

so_IndividualEstimates_create_Estimates <- function(self) {
	.Call("r_so_IndividualEstimates_create_Estimates", self)
}

so_IndividualEstimates_get_RandomEffects <- function(self) {
	.Call("r_so_IndividualEstimates_get_RandomEffects", self)
}

so_IndividualEstimates_set_RandomEffects <- function(self, value) {
	.Call("r_so_IndividualEstimates_set_RandomEffects", self, value)
}

so_IndividualEstimates_create_RandomEffects <- function(self) {
	.Call("r_so_IndividualEstimates_create_RandomEffects", self)
}

so_IndividualEstimates_get_EtaShrinkage <- function(self) {
	.Call("r_so_IndividualEstimates_get_EtaShrinkage", self)
}

so_IndividualEstimates_set_EtaShrinkage <- function(self, value) {
	.Call("r_so_IndividualEstimates_set_EtaShrinkage", self, value)
}

so_IndividualEstimates_create_EtaShrinkage <- function(self) {
	.Call("r_so_IndividualEstimates_create_EtaShrinkage", self)
}

Estimates_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_IndividualEstimates_get_Estimates(.self$.cobj)
			if (!isnull(child)) {
				so_Estimates_ref(child)
				so_Estimates$new(cobj=child)
			}
		} else {
			if (!is(value, "so_Estimates")) {
				stop("object must be of type 'so_Estimates'")
			}
			so_IndividualEstimates_set_Estimates(.self$.cobj, value$.cobj)
			so_Estimates_ref(value$.cobj)
		}
	}
}

RandomEffects_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			child = so_IndividualEstimates_get_RandomEffects(.self$.cobj)
			if (!isnull(child)) {
				so_RandomEffects_IE_ref(child)
				so_RandomEffects_IE$new(cobj=child)
			}
		} else {
			if (!is(value, "so_RandomEffects_IE")) {
				stop("object must be of type 'so_RandomEffects_IE'")
			}
			so_IndividualEstimates_set_RandomEffects(.self$.cobj, value$.cobj)
			so_RandomEffects_IE_ref(value$.cobj)
		}
	}
}

EtaShrinkage_acc <- function(value)
{
	if (!isnull(.self$.cobj)) {
		if (missing(value)) {
			so_IndividualEstimates_get_EtaShrinkage(.self$.cobj)
		} else {
			if (!is(value, "data.frame")) {
				stop("object must be of type 'data.frame'")
			}
			so_IndividualEstimates_set_EtaShrinkage(.self$.cobj, value)
		}
	}
}

so_IndividualEstimates = setRefClass("so_IndividualEstimates",
	fields=list(
		Estimates = Estimates_acc,
		RandomEffects = RandomEffects_acc,
		EtaShrinkage = EtaShrinkage_acc,
		.cobj = "externalptr"
	),
	methods=list(
		copy = function() {
			copy = so_IndividualEstimates_copy(.self$.cobj)
			so_IndividualEstimates$new(cobj=copy)
		},
		initialize = function(cobj) {
			if (missing(cobj)) {
				.cobj <<- so_IndividualEstimates_new()
			} else {
				.cobj <<- cobj
			}
		},
		finalize = function() {
			so_IndividualEstimates_unref(.self$.cobj)
		}
	)
)
